version: '3'
services:
  app:
    container_name: typeorm.app.mssql
    image: "typeorm.app.mssql"
    build: .
    ports: 
      - "3000:3000"
    restart: always 
    env_file: .env
    depends_on: 
      - typeormdbmssql
    volumes:
      - typeorm-app-mssql:/var/lib/typeorm/app/mssql

  typeormdbmssql:
    container_name: typeorm.db.mssql
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    command: /bin/bash ./entrypoint.sh
    restart: always
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "a1?%fkARF!24x"
      MSSQL_PID: Express
      ACCEPT_EULA: "Y"
    logging:
      driver: none
    volumes:
      - typeorm-db-mssql:/var/lib/typeorm/db/mssql
      - ./libs/core/src/db/mssql/docker-entrypoint.sh:/entrypoint.sh
      - ./libs/core/src/db/mssql/docker-db-init.sh:/db-init.sh
      - ./libs/core/src/db/mssql/testdb.sql:/db-init.sql
      
volumes:
  typeorm-db-mssql:
  typeorm-app-mssql:
