version: '3'
services:
  app:
    container_name: typeorm.app.mysql
    image: "typeorm.app.mysq"
    build: .
    ports: 
      - "3000:3000"
    restart: always 
    env_file: .env
    depends_on: 
      - typeormdbmysql
    volumes:
      - typeorm-app-mysql:/var/lib/typeorm/app/mysql

  typeormdbmysql:
    container_name: typeorm.db.mysql
    image: "mysql:8.0.32"
    restart: always
    ports:
      - "3306:3306"
    command: 
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: "testdb"
      MYSQL_ROOT_PASSWORD: "root"
    logging:
      driver: none
    volumes:
      - typeorm-db-mysql:/var/lib/typeorm/db/mysql
      
volumes:
  typeorm-db-mysql:
  typeorm-app-mysql:
